### ISSUE TITLE
Evalution result of groundtruth is not 1.0

### ISSUE THREAD

**Issue by HaoyiZhu** [jin-s13/COCO-WholeBody#15]
Hi! Thanks for your wonderful work! 

However, when I tried to use your evaluation code, I found a strange thing.
I took the 'annotations' part of your 'coco_wholebody_val_v1.0.json' file and set every element's score to 1.0, then I passed it to evaluate_mAP function as res_file (and the gt_file is still 'coco_wholebody_val_v1.0.json'). The confusing thing is that the result AP is not equal to 1.0 and even very low. 

Is there anything important that I missed? And here is the result:
![image](https://user-images.githubusercontent.com/63538191/106474154-9417bb80-64df-11eb-9f1b-01bd7b42f26d.png)
![image](https://user-images.githubusercontent.com/63538191/106474213-a3970480-64df-11eb-8d4d-61905e8e22aa.png)
![image](https://user-images.githubusercontent.com/63538191/106474241-ab56a900-64df-11eb-84fc-3408f0d801cd.png)

**Comment by luminxu** [comment]
closed via #16

**Comment by luminxu** [comment]
Thanks for your interest in our work. 

According to [cocodataset/cocoapi](https://github.com/cocodataset/cocoapi), the persons that have no any keypoint annotations ([0, 0, 0] for all the joints) are ignored for ground truth, but these cases are not processed in the prediction results automatically when evaluation. They are usually filtered in dataloader code if ground truth detection results are applied.

If you directly put all the ground truth cases into result file, false positives happen when evaluation. You should filter out all the cases without any annotations of the part in the result file, then this part can achieve 1.0 AP.

In order to solve the problem, we polish our evaluation tools and conduct the filter for all-zero cases in the prediction results before compute AP. Now, you can get 1.0 AP using our tools of the revised version, even if you directly compare the ground truth with itself.

**Comment by luminxu** [comment]
closed via #16
