### ISSUE TITLE
Why do foot keypoints tends to merge in ZoomNet and ZoomNAS? 

### ISSUE THREAD

**Issue by koonyook** [jin-s13/COCO-WholeBody#41]
From the qualitative results you published from your ZoomNet paper (figure 12-13) and ZoomNAS paper (figure 11), the majority of them seem to have the big toe and the small toe keypoints merged into one spot and it usually lands at the middle toe. In a few times they split, and both points almost overlap. 

Is this an unintended behavior?
If yes, Is it caused by the error in the dataset or the problem in the model?

**Comment by jin-s13** [comment]
We also noticed that interesting phenomenon. I think it is because the big toe and the small toe are not easy to be distinguished (very close, covered by shoes). 

We checked the data and did not find labeling errors. We also found that in some work (e.g. https://github.com/openpifpaf/openpifpaf, https://arxiv.org/pdf/2211.03375.pdf) , the trained models can successfully distinguish these two keypoints. This also suggests that the problem is not caused by labeling errors.

Maybe it is related to model training (the foot keypoints are not fully trained). I guess increasing the loss weight of foot keypoints may help. But I have not tried that.
