### ISSUE TITLE
Float keypoint visibility annotation

### ISSUE THREAD

**Issue by oKatanaaa** [jin-s13/COCO-WholeBody#5]
Hi, thank you very much for making this dataset. I've got a question about annotations.

Some of the annotations (for example, annotation id=193390, lefthand_kpts) have float numbers for the visibility flag instead of integers as described in the DATA_FORMAT file. How to interpret these? Thanks.

![image](https://user-images.githubusercontent.com/43654321/90642451-71505e00-e243-11ea-90a0-c7aaa7799673.png)

**Comment by jin-s13** [comment]
Hi, 
Thanks for asking!
Yes, some annotations may have float visibility. Because in our annotation steps,  before manual inspection&correction, we used on-the-shelf models to generate the psudo-labels. The predicted visibility scores are not deleted, which may be useful for further possible applications.
In our experiments, we just ignore these keypoints with visibility=0, during training/testing. If the visibility of a keypoint > 0, you can safely use it to train the model.
